arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-dir: lib/l10n/gen
output-class: Module1Localizations
output-localization-file: module_1_localizations.dart
synthetic-package: false # set false if you want to import the delegate in another package or app
nullable-getter: false
